### ISSUE TITLE
Improvements for sphinx in dev-setup

### ISSUE THREAD

**Issue by mtnstar** [hitobito/development#51]
# Activate Sphinx in dev-setup

currently sphinx is started as container, but search does not use sphinx since the env variable **RAILS_SPHINX_PORT** is not set by default. Setting RAILS_SPHINX_PORT=9312 in docker/rails.env activates it and it works.

# Generate sphinx config on startup

currently sphinx is just using a static index config: https://github.com/hitobito/development/blob/master/docker/sphinx.conf

so only core attributes are searchable and extended indexes from the wagons are ignored

the goal is to generate the sphinx dynamically on start-up (docker-compose up) with thinking_sphinx gem

# ToDo

- [ ] Activate sphinx search in dev setup by default if there's no veto
- [ ] Fix running of sphinx specs #15 
- [ ] Use dynamically generated sphinx index conf instead of static one
